### ISSUE TITLE
versions 8.0.0 and newer not working with Maven 3.6.3 Java 11/17

### ISSUE THREAD

**Issue by wildcart** [qoomon/maven-git-versioning-extension#230] opened 2023-01-10 19:27 UTC
Dear all,

I am possibly not seeing the obvious but for the last hour or so I've tried to get this Maven extension to work in a very simple test project (Java 11/17 Maven 3.6.3): very simple POM, single application class with single test class (see attached archive). 

Steps:
1. copied `extensions.xml` 'snippet' from `README.md` (using version 9.4.1 of this extension)
2. copied `maven-git-versioning-extension.xml` 'snippet' from `README.md`
3. run `mvn --debug package`
  (log files: `mvn-*`)
4. run `mvn help:evaluate -Dexpression=project.version -q -DforceStdout`
  (log files: `git-versioning-*.stdout`)
5. run `mvn help:evaluate -Dexpression=project.version -Dorg.slf4j.simpleLogger.log.me.qoomon.maven.gitversioning=debug` 
  (log files: `git-versioning-*.debug`)

Observed:
* `.git-versioned-pom.xml` is not created
3. created JAR file: `target/deploy-0.0.0-SNAPSHOT` (_deploy_ is the project/artifact name)
4. output: `0.0.0-SNAPSHOT`

Expected:
* `.git-versioned-pom.xml` created in project root directory 
3. created JAR file `deploy-versioning-SNAPSHOT.jar` (_versioning_ is the branch name)
4. output: `versioning-SNAPSHOT`

_Expected_ are actually the results that I get when I downgrade this extension to version 7.4.0 without changing anything else. When I downgrade the extension I also get the extension's output in the Maven output (which is missing when using 9.4.1):
```
[INFO] --- me.qoomon:maven-git-versioning-extension:7.4.0 [core extension] ----
[INFO] matching ref: BRANCH - versioning
[INFO] ref configuration: BRANCH - pattern: .+
[INFO]   version: ${ref}-SNAPSHOT
[INFO]   properties: ${ref}-SNAPSHOT
[INFO]     foo - ${ref}
[INFO]
[INFO] playground:deploy
[INFO] project version: versioning-SNAPSHOT
```

Maven is run with Java 11:
```
$ mvn --version
Apache Maven 3.6.3 (SUSE 3.6.3-4.2.1)
Maven home: /usr/share/maven
Java version: 11.0.17, vendor: Oracle Corporation, runtime: /usr/lib64/jvm/java-11-openjdk-11
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.3.18-150300.59.101-default", arch: "amd64", family: "unix"
```

but the project uses Adoptium's Temurin 17 JDK for the build:
```
[INFO] --- maven-toolchains-plugin:3.1.0:toolchain (default) @ deploy ---
[INFO] Required toolchain: jdk [ vendor='Eclipse Adoptium' version='17' ]
[INFO] Found matching toolchain for type jdk: JDK[/usr/lib64/jvm/temurin-17-jdk]
```

Removing the _toolchain_ from the POM and using OpenJDK 11 instead, makes no difference.

I've attached a project archive that demonstrates the problem (disabled the toolchain plugin for testing) and which contains log files of the commands listed above. The `mvn --debug packge` log file indicates the the extension is found even when using 9.4.1 it is 'simply' not executed.

I did, however, remove the `.git` directory as it contained sensitive information. Running the above `mvn package` command without having the `.git` directory reports a _warning_ with version 7.4.0:
```
[INFO] --- me.qoomon:maven-git-versioning-extension:7.4.0 [core extension] ----
[WARNING] skip - project is not part of a git repositor
```

which is not reported when using version 9.4.1. I've also tried version 8.0.0 and 9.3.0, all of which do not work for me. Interestingly, the README.md tells me that version 8.0.0 is the first to require Java 11 and drop Java 8 support which is a requirement I think I meet (see above).

Like I said I am probably missing the obvious but as of right now I am at a complete loss and any help would be appreciated.

**Comment by qoomon** [comment] 2023-01-11 08:32
Sounds strange, I'll have look, however I can't find the attached project.

**Comment by qoomon** [comment] 2023-01-11 10:39
I'm not able to reproduce any of your issues with maven 3.8.7 and java openjdk 11.0.17.

**Comment by wildcart** [comment] 2023-01-11 13:56
thanks for looking into this and the quick response. I'll try to update Maven and check if that helps. If not, do you have any idea how I can debug this issue any further?

**Comment by wildcart** [comment] 2023-01-11 13:58
I just realized that I missed to attache the archive referenced in the my original post :(

For completeness: 
[maven-git-versioning-test-20230110.tar.gz](https://github.com/qoomon/maven-git-versioning-extension/files/10393027/maven-git-versioning-test-20230110.tar.gz)

**Comment by wildcart** [comment] 2023-01-11 14:14
upgrading Maven to 3.8.7 fixes the issue:
```
$ mvn --version
Apache Maven 3.8.7 (b89d5959fcde851dcb1c8946a785a163f14e1e29)
Maven home: /home/user/opt/apache-maven
Java version: 11.0.17, vendor: Oracle Corporation, runtime: /usr/lib64/jvm/java-11-openjdk-11
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.3.18-150300.59.101-default", arch: "amd64", family: "unix"

$ mvn package
[...]
[INFO] --- me.qoomon:maven-git-versioning-extension:9.4.1 [core extension] ----
[INFO] matching ref: BRANCH - versioning
[INFO] ref configuration: BRANCH - pattern: .+
[INFO]   version: ${ref}-SNAPSHOT
[INFO]   properties: ${ref}-SNAPSHOT
[INFO]     foo - ${ref}
[INFO]
[INFO] playground:deploy
[INFO] set version to versioning-SNAPSHOT
```

Thanks again for the quick response.

**Comment by qoomon** [comment] 2023-01-11 14:33
Glad to hear that, I think I remember a strange bug in maven some time ago that was fixed in the latest version.

**Closed by qoomon** 2023-01-11 14:33 UTC

**Comment by qoomon** [comment] 2023-01-11 14:39
I found it see https://github.com/qoomon/maven-git-versioning-extension/blob/0f649b951294bde8eecf8c391d75fddb3aaf0ad4/src/main/java/org/apache/maven/model/building/DefaultModelProcessor.java the injection was broken, introduced in maven version `3.6.1`

**Comment by wildcart** [comment] 2023-01-11 14:43
I've seen a closed issue related to _not working with Maven 3.6.2_ but this affected a version quite some time before 7.x of this extension. Since 7.4.0 worked for me with Maven 3.6.3 I thought this issue to be fixed in either Maven or this extension and didn't bother checking for Maven updates. Anyways, it's working for me now. 

Thanks.
