### ISSUE TITLE
Prevent replacement of properties

### ISSUE THREAD

**Issue by reitzmichnicht** [qoomon/maven-git-versioning-extension#194] opened 2022-05-31 10:04 UTC
I don't know which version introduced the changed behaviour. I'm using version 8.0.0 now and I have a section like this in the pom.xml

```
<properties>
<project.build.outputTimestamp>${git.commit.timestamp.datetime}</project.build.outputTimestamp>
</properties>
```

Everytime I run mvn commands like this:
mvn versions:set -DnewVersion=1.2.3-SNAPSHOT
The placeholder is replaced with the timestamp in the original pom.xml although I have not enabled any updatePom setting.

**Comment by qoomon** [comment] 2022-06-01 11:13
That is strange, I'll investigate.

**Comment by qoomon** [comment] 2022-06-01 12:03
Sorry but I can't reproduce this behaviour. Could you upload a simple zipped example project to reproduce this behaviour to this issue?

**Comment by qoomon** [comment] 2022-06-05 19:03
It turns out this behaviour is not caused by the maven-git-versioning-extension. If I run `mvn versions:set -DnewVersion=1.2.3` and the pom version was not equals to `1.2.3` and there is a `<project.build.outputTimestamp>` property defined than this property gets set by the maven versions plugin.

**Comment by qoomon** [comment] 2022-06-05 19:07
This versions-maven-plugin behaviour was introduced by this merge https://github.com/mojohaus/versions-maven-plugin/pull/522

**Comment by qoomon** [comment] 2022-06-05 19:42
I'm thinking about implement the same logic. Means override `<project.build.outputTimestamp>` with commit timestamp, if property is present. So you don't have to have a property like `<project.build.outputTimestamp>${git.commit.timestamp.datetime}</project.build.outputTimestamp>`.

WDYT?

BTW I plan to remove basically all `${git....}` properties, because they are not resolved by default and therefore their values are not part of the published pom.xml. Instead you should make use of the `<properties>` within the extension config file e.g.
```xml
<ref type="branch">
    <pattern>.+</pattern>
    <version>${ref}-SNAPSHOT</version>
    <properties>
        <foo>${commit.timestamp.datetime}</foo>
    </properties>
</ref>
```

**Comment by reitzmichnicht** [comment] 2022-06-07 09:45
Sorry about filling non related bugs here, but thanks for the investigation. Always a joy to see new features introduced with changing the old defaults.

For me it would also be fine to define/use the git properties via the extension config.
With the release process our highest problem is that we still want to use some checks of the release:prepare step and that this relies on a snapshot version defined, so the whole process is segregated into steps with this extension enabled/disabled

Kind regards,
Michael

**Closed** 2022-06-07 22:02 UTC

**Comment by qoomon** [comment] 2022-08-15 13:08
Following merge of the version plugin adds an option to set behaviour of updating of `project.build.outputTimestamp` see https://github.com/mojohaus/versions-maven-plugin/pull/630
