### ISSUE TITLE
Failure on multi-project with aggregation and external parent on modules

### ISSUE THREAD

**Issue by klinamen** [qoomon/maven-git-versioning-extension#39] opened 2019-05-20 21:32 UTC
Fixing #37 broke the feature introduced with #34 in a specific use-case that had no tests for.
In particular, it seems that the changes introduced in me.qoomon.maven.gitversioning.ModelProcessor#getParentPom do not take into account the case where one module exists having an external POM as a parent (e.g. a spring boot starter), and a version mismatch exception is thrown, making the build to fail.

**Comment by klinamen** [comment] 2019-05-20 21:35
Just reverting changes to ModelProcessor.getParentPom does the job, but I cannot run the entire test suite on a Windows machine, so I did not provide a working solution yet. I'll try to sketch a solution on a different workstation, as soon as I can.

**Comment by qoomon** [comment] 2019-05-21 06:30
Sorry for the inconvenience, I will have a look right away

**Comment by qoomon** [comment] 2019-05-21 06:47
I think I found the root cause. The question is how to determine the location of the `...pom` file, of an external project.
`me.qoomon.maven.gitversioning.ModelProcessor`
```java
    private File getParentPom(Model projectModel) {
        if (projectModel.getParent() == null) {
            return null;
        }

        File parentPom = new File(projectModel.getProjectDirectory(), projectModel.getParent().getRelativePath());
        if (parentPom.isDirectory()) {
            parentPom = new File(parentPom, "pom.xml");
        }
        return parentPom;
    }

```

**Comment by qoomon** [comment] 2019-05-21 11:31
Fixed in version 4.2.3

**Comment by klinamen** [comment] 2019-05-21 15:23
Thanks a lot. Hope to see the fixed version on Maven Central soon!

**Comment by qoomon** [comment] 2019-05-21 15:25
try again in 15 minutes, I've just released it.

**Closed** 2019-05-21 16:05 UTC
Labels: bug
