### ISSUE TITLE
Version 5.0.0 not working with maven 3.6.2

### ISSUE THREAD

**Issue by wlodarczyk-lukasz** [qoomon/maven-git-versioning-extension#69] opened 2020-03-10 09:41 UTC
Hi, after updating version from `4.10.2` to `5.0.1` I found out that artifacts are not build locally, we're using CircleCI as well and there everything seems to be OK. I am running `OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.5+10)` and `Apache Maven 3.6.2`

**Comment by qoomon** [comment] 2020-03-11 12:56
could you provide a simple example repository where this issue is reproduced.

**Comment by jmpavlec** [comment] 2020-03-12 09:32
How about your own repo? 
https://github.com/qoomon/maven-git-versioning-extension/pull/70

I used the same xml for the install/config from your documentation. When I use 4.10.2 it works, but 5.0.1, it does not (locally).

**Comment by qoomon** [comment] 2020-03-12 14:12
hmm maybe its because of maven `3.6.2` with `3.6.3` it works as expected.

**Comment by qoomon** [comment] 2020-03-12 14:18
It is because of version `3.6.2` I just verified that. I will investigate why this is

**Comment by qoomon** [comment] 2020-03-12 14:50
I fixed it in extension version `5.0.3` will released in a couple of minutes.

**Comment by wlodarczyk-lukasz** [comment] 2020-03-12 15:35
Cool, thank you very much for really quick fix! 👍

**Comment by qoomon** [comment] 2020-03-13 16:31
You're welcome.

**Closed by qoomon** 2020-03-13 16:31 UTC
Labels: bug

**Comment by jmpavlec** [comment] 2020-03-16 09:04
Not seeing the 5.0.3 release yet anywhere. Would also be nice to include that version in the README.md (still shows 4.10.0)

e.g. https://github.com/qoomon/maven-git-versioning-extension/blob/master/README.md#L36

**Comment by qoomon** [comment] 2020-03-16 17:13
5.0.2 ist the right one, I made a typo 🙄
https://search.maven.org/artifact/me.qoomon/maven-git-versioning-extension/5.0.2/maven-plugin
