### ISSUE TITLE
Null pointer in multi-module

### ISSUE THREAD

**Issue by ajanelle** [qoomon/maven-git-versioning-extension#26] opened 2019-02-27 18:58 UTC
We are having a null pointer when generating a multi module project. The problem is cause because we dont have the version tag in the child project.

my child POM

```
       <parent>
               <groupId>com.myComp.document</groupId>
               <artifactId>document-business-processes</artifactId>
               <version>0.0.0.5-SNAPSHOT</version><relativePath>..</relativePath>
       </parent>
       <artifactId>document-business-processes-contract</artifactId>
       <name>Document Business Processes Contract</name>
       
       .....
```

The stack trace

```
Non-readable POM C:\Data\eclipse-2018\document-business-processes\document-business-processes-contract\pom.xml: Git Versioning Model Processor: NullPointerException
java.io.IOException: Git Versioning Model Processor
    at me.qoomon.maven.gitversioning.GitVersioningModelProcessor.processModel (GitVersioningModelProcessor.java:194)
    at me.qoomon.maven.gitversioning.GitVersioningModelProcessor.read (GitVersioningModelProcessor.java:73)
    at org.apache.maven.model.building.DefaultModelBuilder.readModel (DefaultModelBuilder.java:536)
    at org.apache.maven.model.building.DefaultModelBuilder.build (DefaultModelBuilder.java:276)
    at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:432)
    at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:400)
    at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:363)
    at org.apache.maven.graph.DefaultGraphBuilder.collectProjects (DefaultGraphBuilder.java:414)
    at org.apache.maven.graph.DefaultGraphBuilder.getProjectsForMavenReactor (DefaultGraphBuilder.java:405)
    at org.apache.maven.graph.DefaultGraphBuilder.build (DefaultGraphBuilder.java:82)
    at org.apache.maven.DefaultMaven.buildGraph (DefaultMaven.java:507)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:219)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:954)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:288)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:192)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
Caused by: java.lang.NullPointerException
    at me.qoomon.gitversioning.GitVersioning.determineVersion (GitVersioning.java:70)
    at me.qoomon.maven.gitversioning.GitVersioningModelProcessor.processModel (GitVersioningModelProcessor.java:135)
    at me.qoomon.maven.gitversioning.GitVersioningModelProcessor.read (GitVersioningModelProcessor.java:73)
    at org.apache.maven.model.building.DefaultModelBuilder.readModel (DefaultModelBuilder.java:536)
    at org.apache.maven.model.building.DefaultModelBuilder.build (DefaultModelBuilder.java:276)
    at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:432)
    at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:400)
    at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:363)
    at org.apache.maven.graph.DefaultGraphBuilder.collectProjects (DefaultGraphBuilder.java:414)
    at org.apache.maven.graph.DefaultGraphBuilder.getProjectsForMavenReactor (DefaultGraphBuilder.java:405)
    at org.apache.maven.graph.DefaultGraphBuilder.build (DefaultGraphBuilder.java:82)
    at org.apache.maven.DefaultMaven.buildGraph (DefaultMaven.java:507)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:219)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:954)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:288)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:192)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
```

**Comment by qoomon** [comment] 2019-02-27 20:17
Thx for reporting will fix that tomorrow.

**Comment by qoomon** [comment] 2019-02-27 20:37
should be fixed in version `4.0.1`

**Comment by qoomon** [comment] 2019-02-27 21:49
Do you executing `mvn` command from within project root directory?

**Comment by ajanelle** [comment] 2019-02-28 14:51
Thanks for the quick reply and fix!
I'm executing it from eclipse directly on the child module does it change anything?
Maybe I'm doing something wrong, the created artifact doesn't have the branch name in it. I can see in the log that your extension is call and seem to have done its job but the final file doesn't seem to have been modified... 
When I try in a project not in a multiple module context it work perfectly.

The log : 

```
[INFO] Scanning for projects...
[INFO] 
[INFO] --- maven-git-versioning-extension:4.0.1 ---
[INFO] document-business-processes-contract - git versioning 0.0.0.5-SNAPSHOT -> 0.0.0.5-SNAPSHOT-print-option-SNAPSHOT (branch:feature/print-option)
[INFO] document-business-processes - git versioning 0.0.0.5-SNAPSHOT -> 0.0.0.5-SNAPSHOT-print-option-SNAPSHOT (branch:feature/print-option)
[INFO] 
[INFO] -----< com.myComp.document:document-business-processes-contract >-----
[INFO] Building Document Business Processes Contract 0.0.0.5-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-jaxb2-plugin:0.13.3:generate (default) @ document-business-processes-contract ---
[INFO] Latest timestamp of the source resources is [2019-02-27 13:55:58.140], earliest timestamp of the target resources is [2019-02-27 13:56:01.415].
[INFO] Sources are up-to-date, XJC will be skipped.
[INFO] 
[INFO] --- maven-resources-plugin:3.0.1:resources (default-resources) @ document-business-processes-contract ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 0 resource
[INFO] Copying 226 resources
[INFO] Copying 1 resource
[INFO] 
[INFO] --- maven-compiler-plugin:3.7.0:compile (default-compile) @ document-business-processes-contract ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-resources-plugin:3.0.1:testResources (default-testResources) @ document-business-processes-contract ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory C:\Data\eclipse-2018\document-business-processes\document-business-processes-contract\src\test\resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.7.0:testCompile (default-testCompile) @ document-business-processes-contract ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-surefire-plugin:2.21.0:test (default-test) @ document-business-processes-contract ---
[INFO] 
[INFO] --- maven-git-versioning-extension:4.0.1:pom-replacement (pom-replacement) @ document-business-processes-contract ---
[INFO] 
[INFO] --- maven-jar-plugin:3.0.2:jar (default-jar) @ document-business-processes-contract ---
[INFO] Building jar: C:\Data\eclipse-2018\document-business-processes\document-business-processes-contract\target\document-business-processes-contract-0.0.0.5-SNAPSHOT.jar
[INFO] 
[INFO] --- maven-install-plugin:2.5.2:install (default-install) @ document-business-processes-contract ---
[INFO] Installing C:\Data\eclipse-2018\document-business-processes\document-business-processes-contract\target\document-business-processes-contract-0.0.0.5-SNAPSHOT.jar to C:\Users\rpwte759\.m2\repository\com\myComp\document\document-business-processes-contract\0.0.0.5-SNAPSHOT\document-business-processes-contract-0.0.0.5-SNAPSHOT.jar
[INFO] Installing C:\Data\eclipse-2018\document-business-processes\document-business-processes-contract\.git-versioned.pom.xml to C:\Users\rpwte759\.m2\repository\com\myComp\document\document-business-processes-contract\0.0.0.5-SNAPSHOT\document-business-processes-contract-0.0.0.5-SNAPSHOT.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 11.282 s
[INFO] Finished at: 2019-02-28T09:36:58-05:00
[INFO] ------------------------------------------------------------------------
```

my complete pom.xml

```
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

	<modelVersion>4.0.0</modelVersion>

	<parent>
		<groupId>com.myComp.document</groupId>
  	  	<artifactId>document-business-processes</artifactId>
	  	<version>0.0.0.5-SNAPSHOT</version>
		<relativePath>..</relativePath>
	</parent>

	<artifactId>document-business-processes-contract</artifactId>
	<name>Document Business Processes Contract</name>
	
	<properties>
		<maven.compiler.source>1.8</maven.compiler.source>
		<maven.compiler.target>1.8</maven.compiler.target>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
	</properties>

	<build>
		<plugins>
			<plugin>
				<groupId>org.jvnet.jaxb2.maven2</groupId>
				<artifactId>maven-jaxb2-plugin</artifactId>
				<version>0.13.3</version>
				<executions>
					<execution>
						<goals>
							<goal>generate</goal>
						</goals>
					</execution>
				</executions>
				<configuration>
					<schemaDirectory>${project.basedir}/src/main/resources/document/service/v1</schemaDirectory>
					<schemaIncludes>
						<include>*.wsdl</include>
					</schemaIncludes>
					<bindingDirectory>${project.basedir}/src/main/resources/document/model/bindings</bindingDirectory>
					<bindingIncludes>
						<include>**/*.xjb</include>
					</bindingIncludes>
				</configuration>
			</plugin>
		</plugins>
	</build>

</project>
```

**Comment by qoomon** [comment] 2019-02-28 17:39
In general it's very bad practice to execute maven within module
directories. You should always call build you module from project root
directory. You can pass the module as mvn parameter to build just a special
one.
I'm in hurry right now I will give a better explanation next week.

**Comment by ajanelle** [comment] 2019-02-28 21:00
It look like there is still a bug somewhere with the version, I had to add the <version> tag in the child in order to make it work. But after adding it and running from the root it work well thanks for the tips!

Don't rush yourself to respond, have a great weekend :smiley: !

**Comment by qoomon** [comment] 2019-02-28 21:54
What tag?

**Comment by ajanelle** [comment] 2019-02-28 21:56
The `<version>` tag

**Comment by qoomon** [comment] 2019-02-28 21:59
Could you provide a broken and the working setup as a repository?

**Comment by qoomon** [comment] 2019-03-04 08:49
I've just found the root cause, it is because of the relative path tag, my extension is not aware of that. I will fix it this afternoon.

**Comment by qoomon** [comment] 2019-03-04 22:46
It should work now from project root directory as well as from child module directory(even though it is bad practice) #v4.0.2

**Comment by ajanelle** [comment] 2019-03-05 14:13
I've just test it and its work well from both root and child module.
Thanks!

**Closed** 2019-03-05 14:14 UTC
