### ISSUE TITLE
Can I Update of version for parent?

### ISSUE THREAD

**Issue by chanjetsdp** [qoomon/maven-git-versioning-extension#147] opened 2021-11-06 06:26 UTC
how can I update  version for parent ?

 0.0.0 to 1.0.0-branch_name-SNAPSHOT

```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.xxx.daas</groupId>
        <artifactId>daas-domain-parent</artifactId>
        <version>0.0.0</version>
    </parent>
    <groupId>com.xxx.laas</groupId>
    <artifactId>laas-common</artifactId>
    <packaging>jar</packaging>
    <version>1.0.0-branch_name-SNAPSHOT</version>
</projectt>
```

**Comment by qoomon** [comment] 2021-11-06 12:28
currently that's not possible, however I should be able to add this feature within the next week if you really need this.

**Comment by qoomon** [comment] 2021-11-06 12:31
config could look like this. WDYT
```xml
<ref type="branch">
    <pattern>.+</pattern>
    <parentVersion>${ref}-SNAPSHOT</parentVersion>
    <version>${ref}-SNAPSHOT</version>
    <properties>
        <foo>${ref}</foo>
    </properties>
</ref>
```

**Comment by chanjetsdp** [comment] 2021-11-07 12:54
@qoomon Our team really need this enhancement. thanks for your work.

**Comment by qoomon** [comment] 2021-11-08 07:17
Hi @chanjetsdp, I'm afraid it's not that easy as I thought.
The extension config applies to all pom files in the project, means there can be different parents in each pom file. 

Another issue would be that a parent could by part of the project itself and therefore could have two ambiguous version formats (one from `<version>` and the other from `<parentVersion>`)

I'm not sure how an easy config could look like. Do you have any idea?

**Comment by chanjetsdp** [comment] 2021-11-08 09:10
> Hi @chanjetsdp, I'm afraid it's not that easy as I thought. The extension config applies to all pom files in the project, means there can be different parents in each pom file.
> 
> Another issue would be that a parent could by part of the project itself and therefore could have two ambiguous version formats (one from `<version>` and the other from `<parentVersion>`)
> 
> I'm not sure how an easy config could look like. Do you have any idea?

In our case, we want set the parentVersion same as project version. 
Can you add an configuration as to set ParentVersion Same As PorjectVersion?

**Comment by chanjetsdp** [comment] 2021-11-08 10:43
I build this project locally ` mvn verify install -P release `.  but the extension doesn't work now. 


```
diff --git a/pom.xml b/pom.xml
index be6b544..c255eff 100644
--- a/pom.xml
+++ b/pom.xml
@@ -212,37 +212,6 @@
                         </executions>
                     </plugin>
 
-                    <plugin>
-                        <groupId>org.apache.maven.plugins</groupId>
-                        <artifactId>maven-gpg-plugin</artifactId>
-                        <version>3.0.1</version>
-                        <executions>
-                            <execution>
-                                <id>sign-artifacts</id>
-                                <phase>package</phase>
-                                <goals>
-                                    <goal>sign</goal>
-                                </goals>
-                                <configuration>
-                                    <gpgArguments>
-                                        <arg>--pinentry-mode</arg>
-                                        <arg>loopback</arg>j
-                                    </gpgArguments>
-                                </configuration>
-                            </execution>
-                        </executions>
-                    </plugin>
-                    <plugin>
-                        <groupId>org.sonatype.plugins</groupId>
-                        <artifactId>nexus-staging-maven-plugin</artifactId>
-                        <version>1.6.8</version>
-                        <extensions>true</extensions>
-                        <configuration>
-                            <serverId>sonatype-nexus-staging</serverId>
-                            <nexusUrl>https://oss.sonatype.org</nexusUrl>
-                            <autoReleaseAfterClose>true</autoReleaseAfterClose>
-                        </configuration>
-                    </plugin>
                 </plugins>
             </build>
         </profile>
```

**Comment by qoomon** [comment] 2021-11-08 10:48
what's the error?

**Comment by qoomon** [comment] 2021-11-08 10:49
and you don't need to use the release profile `-P release`

**Comment by chanjetsdp** [comment] 2021-11-08 14:12
> what's the error?

`mvn -X -U help:evaluate -Dexpression=project.version -Dorg.slf4j.simpleLogger.log.me.qoomon.maven.gitversioning=debug`

**_[INFO] --- me.qoomon:maven-git-versioning-extension:7.1.2 [core extension] ----_**  is **NOT** show after **_Scanning for projects..._**
```
[INFO] Scanning for projects...
[INFO] 
[INFO] --- me.qoomon:maven-git-versioning-extension:7.1.2 [core extension] ----
```

**Comment by chanjetsdp** [comment] 2021-11-08 14:42
> and you don't need to use the release profile `-P release`

I resolved the problem.  (the reason was I modify the version as 7.1.2-xn at first,  but then I revert it ,and then installed local with 7.1.2). 


It seems works ( update the parent version) after I add these lines:

``` diff
diff --git a/src/main/java/me/qoomon/maven/gitversioning/GitVersioningModelProcessor.java b/src/main/java/me/qoomon/maven/gitversioning/GitVersioningModelProcessor.java
index 14d24e2..32fd2f2 100644
--- a/src/main/java/me/qoomon/maven/gitversioning/GitVersioningModelProcessor.java
+++ b/src/main/java/me/qoomon/maven/gitversioning/GitVersioningModelProcessor.java
@@ -341,6 +341,10 @@ public class GitVersioningModelProcessor extends DefaultModelProcessor {
                 String gitVersion = getGitVersion(versionFormat, parentGAV);
                 logger.debug("set parent version to " + gitVersion + " (" + parentGAV + ")");
                 parent.setVersion(gitVersion);
+            } else {
+                String gitVersion = getGitVersion(versionFormat, parentGAV);
+                logger.debug("xn:: set parent version to " + gitVersion + " (" + parentGAV + ")");
+                parent.setVersion(gitVersion);
             }
         }
     }

```

**Comment by chanjetsdp** [comment] 2021-11-08 15:13
> Hi @chanjetsdp, I'm afraid it's not that easy as I thought. The extension config applies to all pom files in the project, means there can be different parents in each pom file.
> 
> Another issue would be that a parent could by part of the project itself and therefore could have two ambiguous version formats (one from `<version>` and the other from `<parentVersion>`)
> 
> I'm not sure how an easy config could look like. Do you have any idea?

Thanks for your immediate response.
And I think this is not a general requirement,  so I can fork this repo  and  handle it myself.

**Comment by thomschke** [comment] 2022-01-12 06:46
I need this enhancement too: sync `<parentVersion>` with `version` if empty `relativePath`. @chanjetsdp Can you publish your changes?

**Comment by qoomon** [comment] 2022-01-12 08:02
@thomschke I had a look into that feature request again. I could implement this feature by adding a new `relatedProjects` section to `git-versioning-extension.xml` config file. Something like the following. All `relatedProjects` would get their versions updated as well. I'm not sure about the wording `relatedProjects`, maybe you have a better wording idea. WDYT?
<configuration>

  <relatedProjects>
    <project>
      <groupId>me.qoomon</groupId>
      <artifactId>example</artifactId>
    </project>
  </relatedProjects>
    
</configuration>
```

**Comment by thomschke** [comment] 2022-01-12 12:19
YES ... !!!

**Comment by qoomon** [comment] 2022-01-12 12:22
@thomschke do you think `relatedProjects` is easy to understand? or should we choose another wording?

**Comment by thomschke** [comment] 2022-01-12 12:29
All related projects will be released at the same time. 
I think the wording `releatedProjects` is ok ... but you can also call it `releaseBundle` or `billOfMaterials`or ... :-)

**Comment by qoomon** [comment] 2022-01-12 18:23
Should work with version `7.2.0`

**Comment by qoomon** [comment] 2022-01-12 18:28
Please confirm if it is working.

**Comment by thomschke** [comment] 2022-01-12 23:28
It works as expected ... GJ ... THANKS !!!

**Comment by thomschke** [comment] 2022-01-14 10:14
Hi @qoomon, if you are using a git worktree (#153) **and** start a mvn process inside a sub-module (not root-module) then the `relatedProjects` will not be considered. Sorry for my incomplete testing, can you fixed this asap?

**Comment by qoomon** [comment] 2022-01-14 10:40
@thomschke could you provide an example project and your git commands so I can reproduce your problem?

**Comment by qoomon** [comment] 2022-01-14 11:59
@thomschke please have a try with version `7.2.1`

**Comment by thomschke** [comment] 2022-01-14 14:27
version '7.2.1' don't work ... AND this new version don't work in normal git clones too ... so I have to downgrade to 7.2.0 !!!

**Comment by thomschke** [comment] 2022-01-14 14:48
- `git clone -b main https://github.com/thomschke/mvn-parent.git`
- `mvn install`

1) 
- `git clone -b main https://github.com/thomschke/mvn.git`
- `cd module` and `mvn install`
- it works!

2) 
- `git clone -bare -b main https://github.com/thomschke/mvn.git`
- `git checkout -b dummy`
- `git worktree add ../main` and `cd ../main'
- `cd module` and `mvn install`
- it doesn't work!

**Comment by qoomon** [comment] 2022-01-14 16:03
@thomschke what do you mean by its is not working. I don't have any troubles on my machine. btw wich java version do you use?

**Comment by qoomon** [comment] 2022-01-14 16:08
@thomschke do you execute the git clone of mvn project within the mvn-parent project folder?

**Comment by thomschke** [comment] 2022-01-14 16:10
```
Apache Maven 3.8.4 (9b656c72d54e5bacbed989b64718c159fe39b537)
Maven home: /Applications/apache-maven/3.8.4
Java version: 1.8.0_311, vendor: Oracle Corporation, runtime: /Library/Java/JavaVirtualMachines/jdk1.8.0_311.jdk/Contents/Home/jre
Default locale: de_DE, platform encoding: UTF-8
OS name: "mac os x", version: "10.16", arch: "x86_64", family: "mac"
```

```
[INFO] Scanning for projects...
[INFO] 
[INFO] --- me.qoomon:maven-git-versioning-extension:7.2.0 [core extension] ----
[INFO] matching ref: BRANCH - main
[INFO] ref configuration: BRANCH - pattern: .+
[INFO]   describeTagPattern: .*
[INFO]   version: ${ref.slug}-SNAPSHOT
[INFO] 
===== test:test-module:git isRelated: true
[INFO] test:test-module
===== test:test:git isRelated: false
[INFO] project version: git
[INFO] 
===== test:test:git isRelated: false
Downloading from central: https://repo.maven.apache.org/maven2/test/test-parent/git/test-parent-git.pom
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM for test:test:git: Could not find artifact test:test-parent:pom:git in central (https://repo.maven.apache.org/maven2) and 'parent.relativePath' points at no local POM @ test:test:git, /private/var/folders/xd/ld8wgv8x54jfnsrrrqp9t37m0000gn/T/tmp.kjuy6PKE/main/pom.xml, line 10, column 11
```

**Comment by qoomon** [comment] 2022-01-14 16:20
I"d really like to help, however I cant reproduce the error. Maybe you could just make a zip out of an example project setuo where fails.

**Comment by qoomon** [comment] 2022-01-14 16:25
Never mind. I"can reproduce the error for version `7.2.0`

**Comment by thomschke** [comment] 2022-01-14 16:33
If I use `7.2.1` then this error comes a) in the root module AND b) submodule.

**Comment by qoomon** [comment] 2022-01-14 16:42
despite the debug logs (I forget to remove them before release, shame on me) I have no errors.

**Comment by qoomon** [comment] 2022-01-14 16:44
But you are right there something wrong even if I don"t get an error. I'l investigate

**Comment by qoomon** [comment] 2022-01-14 16:47
Here is an output of my build log
<img width="613" alt="Screenshot 2022-01-14 at 17 45 41" src="https://user-images.githubusercontent.com/3963394/149553055-01e0c6ae-0597-43be-b0be-a1cf7e0da3e1.png">

**Comment by qoomon** [comment] 2022-01-14 16:48
my folder structure is like this
* /tmp
  * /mvn-parent
  * /mvn
  * /main <- worktree from mvn repo

**Comment by qoomon** [comment] 2022-01-14 16:55
even though I can"t reproduce your error, could you try to remove unnecessary `<relativePath>../pom.xml</relativePath>` in module pom.xml

**Comment by qoomon** [comment] 2022-01-14 16:58
I got the problem why I was not able to reproduce your error. I had to clean my ~/.m2/repository dir, because some test packages were present already from other projects

**Comment by qoomon** [comment] 2022-01-14 17:06
sorry, I"m still not able to reproduce your error with version `7.2.1`

**Comment by thomschke** [comment] 2022-01-14 17:51
This is my build log (with 7.2.1):
```
[INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM for test:test:git: test:test-parent:pom:git was not found in https://repo.maven.apache.org/maven2 during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of central has elapsed or updates are forced and 'parent.relativePath' points at no local POM @ line 10, column 11
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project test:test:git (/Users/frank/dev/github.com/thomschke/mvn-link/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for test:test:git: test:test-parent:pom:git was not found in https://repo.maven.apache.org/maven2 during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of central has elapsed or updates are forced and 'parent.relativePath' points at no local POM @ line 10, column 11 -> [Help 2]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException
```

**Comment by thomschke** [comment] 2022-01-14 17:52
Same problem occurs when I started the mvn process inside the submodule.

**Comment by qoomon** [comment] 2022-01-14 17:55
It seems like the extension is not even loaded, cause there is not output of the extension at all.

**Comment by thomschke** [comment] 2022-01-14 17:55
under `7.2.0` the problem occurs **only** inside a submodule with:
```
[INFO] Scanning for projects...
[INFO] 
[INFO] --- me.qoomon:maven-git-versioning-extension:7.2.0 [core extension] ----
[INFO] matching ref: BRANCH - main
[INFO] ref configuration: BRANCH - pattern: .+
[INFO]   describeTagPattern: .*
[INFO]   version: ${ref.slug}-SNAPSHOT
[INFO] 
===== test:test-module:git isRelated: true
[INFO] test:test-module
===== test:test:git isRelated: false
[INFO] project version: git
[INFO] 
===== test:test:git isRelated: false
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM for test:test:git: test:test-parent:pom:git was not found in https://repo.maven.apache.org/maven2 during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of central has elapsed or updates are forced and 'parent.relativePath' points at no local POM @ test:test:git, /private/var/folders/xd/ld8wgv8x54jfnsrrrqp9t37m0000gn/T/tmp.kjuy6PKE/main/pom.xml, line 10, column 11
```

**Comment by qoomon** [comment] 2022-01-14 17:56
I think I need a zip file with exactly your scenario, your java version and maven version and os and os version.

**Comment by thomschke** [comment] 2022-01-14 18:16
```
Apache Maven 3.8.4 (9b656c72d54e5bacbed989b64718c159fe39b537)
Maven home: /Applications/apache-maven/3.8.4
Java version: 1.8.0_311, vendor: Oracle Corporation, runtime: /Library/Java/JavaVirtualMachines/jdk1.8.0_311.jdk/Contents/Home/jre
Default locale: de_DE, platform encoding: UTF-8
OS name: "mac os x", version: "10.16", arch: "x86_64", family: "mac"
```

`MacOS 11.6`
`git version 2.34.1`

It's tricky to zip this scenario because the git main repo managements the worktree's with absolute paths
so this are my steps:

```
# ❯ git clone -bare -b main https://github.com/thomschke/mvn.git
Klone nach 'mvn'...
remote: Enumerating objects: 9, done.
remote: Counting objects: 100% (9/9), done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 9 (delta 1), reused 9 (delta 1), pack-reused 0
Empfange Objekte: 100% (9/9), fertig.
Löse Unterschiede auf: 100% (1/1), fertig.

# ❯ cd mvn              

# ❯ git checkout -b test
Zu neuem Branch 'test' gewechselt

# ❯ git worktree add ../main 
Bereite Arbeitsverzeichnis vor (checke 'main' aus)
HEAD ist jetzt bei 71ebd91 Initial work

# ❯ cd ../main

# ❯ mvn -q package
===== test:test:git isRelated: true
===== test:test-parent:git isRelated: true
===== test:test-parent:main-SNAPSHOT isRelated: true
===== test:test-module:git isRelated: true
===== test:test:git isRelated: true
===== test:test:git isRelated: true
===== test:test-parent:main-SNAPSHOT isRelated: true
===== me.qoomon:maven-git-versioning-extension:7.2.0 isRelated: false
===== me.qoomon:maven-git-versioning-extension:7.2.0 isRelated: false
===== org.apache.maven:maven-plugin-api:3.8.2 isRelated: false

# ❯ sed -ir 's|7.2.0|7.2.1|' .mvn/extensions.xml 

# ❯ mvn -q package                                
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM for test:test:git: test:test-parent:pom:git was not found in https://repo.maven.apache.org/maven2 during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of central has elapsed or updates are forced and 'parent.relativePath' points at no local POM @ line 10, column 11
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project test:test:git (/private/var/folders/xd/ld8wgv8x54jfnsrrrqp9t37m0000gn/T/tmp.URjT8sRI/main/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for test:test:git: test:test-parent:pom:git was not found in https://repo.maven.apache.org/maven2 during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of central has elapsed or updates are forced and 'parent.relativePath' points at no local POM @ line 10, column 11 -> [Help 2]
[ERROR] 
```

**Comment by thomschke** [comment] 2022-01-14 18:25
I missed your release `7.2.1` on github ... so I can't compare `7.2.0` and `7.2.1`.

**Comment by qoomon** [comment] 2022-01-14 19:36
Okay I'll give it a try tomorrow. Thanks for your patience.

**Comment by qoomon** [comment] 2022-01-15 23:54
I replayed exactly your steps, however everything works as expected :-/ 

could you try version `7.2.2`. I just removed the unnecessary debug logs.

**Comment by thomschke** [comment] 2022-01-16 08:43
I've made a Dockerfile, please checkout https://github.com/thomschke/mvn-docker.git and run `docker build .`

**Comment by qoomon** [comment] 2022-01-16 13:05
okay that great, this way I can reproduce the error

**Comment by qoomon** [comment] 2022-01-16 13:19
I think I found the problem, I accidentally compiled for java 11 because I made use of java.io.Files

**Comment by qoomon** [comment] 2022-01-16 13:33
I'll release a fix version `7.2.3`. sorry for the inconvenience.

**Comment by qoomon** [comment] 2022-01-16 13:47
It's released.

**Comment by qoomon** [comment] 2022-01-20 23:36
@thomschke can you confirm it is working?

**Comment by thomschke** [comment] 2022-01-21 01:08
It works ... GJ !!!!

**Closed** 2022-01-21 06:58 UTC
Labels: enhancement
